/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class add */

#ifndef _Included_add
#define _Included_add
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     add
 * Method:    addBook
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_add_addBook
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
