/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class borrow */

#ifndef _Included_borrow
#define _Included_borrow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     borrow
 * Method:    borrowBook
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_borrow_borrowBook
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
