/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class delete */

#ifndef _Included_delete
#define _Included_delete
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     delete
 * Method:    deleteBook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_delete_deleteBook
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
