/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myBooks */

#ifndef _Included_myBooks
#define _Included_myBooks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myBooks
 * Method:    BorrowedBooks
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myBooks_BorrowedBooks
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
