/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class returnback */

#ifndef _Included_returnback
#define _Included_returnback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     returnback
 * Method:    returnBook
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_returnback_returnBook
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
