/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class search */

#ifndef _Included_search
#define _Included_search
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     search
 * Method:    searchBook
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_search_searchBook
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
