/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class signin */

#ifndef _Included_signin
#define _Included_signin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     signin
 * Method:    checkadmin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_signin_checkadmin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     signin
 * Method:    checkuser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_signin_checkuser
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
