/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class update */

#ifndef _Included_update
#define _Included_update
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     update
 * Method:    updateBook
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_update_updateBook
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
