/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class viewAll */

#ifndef _Included_viewAll
#define _Included_viewAll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     viewAll
 * Method:    viewBooks
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_viewAll_viewBooks
  (JNIEnv *, jobject);

/*
 * Class:     viewAll
 * Method:    searchBook
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_viewAll_searchBook
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
